### ISSUE TITLE
28/03 - Escolher um aplicativo para trabalhar a respeito

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Crunchyroll#1]
## Descrição
Realizar um estudo a respeito dos aplicativos compatíveis com o estudo da disciplina e escolher um

## Tarefas
Escolher um aplicativo 

## Critérios de aceitação
Escolha do aplicativo realizada

**Comment by Mylena-angelica** [comment]
Dei uma olhada nos apps que os grupos de semestres anteriores utilizaram e como sugestão tenho os aplicativos abaixo:

- Twitter
- Pinterest
- Teams
- Shopee
- Google Drive

**Comment by kaua-pt** [comment]
Aplicativo escolhido : Crunchyrool
