### ISSUE TITLE
Criar a gitpage 

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Crunchyroll#3]
## Descrição
Criar a gitpage, contendo sobre, atas e planejamento
https://requisitos-de-software.github.io/2022.2-Lichess/

## Tarefas
- [x] Criar a git page

## Critérios de aceitação
Gitpage criada

**Comment by Mylena-angelica** [comment]
Decidimos utilizar o Mkdocs para fazer a gitpage.

**Comment by Mylena-angelica** [comment]
Eu e a Ana terminamos a versão 1 da gitpage e fizemos o deploy.

A gitpage foi criada em uma branch. 

@ian-dcg A página está pronta para revisão

**Comment by ananorberto** [comment]
Foi realizado o deploy da versão mais recente da GitPage no [link](https://requisitos-de-software.github.io/2023.1-Crunchyroll/).
A Issue #3 poderá ser fechada assim que o Pull Request for revisado e aprovado.
