### ISSUE TITLE
Criar documentos para a sessão de planejamento

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Crunchyroll#4]
## Descrição
Criar documentos para a sessão de planejamento

## Tarefas
- [x] Metodologias 
- [x] Ferramentas
- [x] Rich Picture
- [x] App Selecionado

## Critérios de aceitação
Documentos confeccionados.

**Comment by Mylena-angelica** [comment]
Toda a documentação está feita e já implementada na gitpage
