### ISSUE TITLE
Rich Picture

### ISSUE THREAD

**Issue by Beatrizvn** [Requisitos-de-Software/2023.1-Crunchyroll#6]
## Descrição
Criar a rich picture do crunchyroll
## Tarefas

- [x] Criação da rich picture
- [x] Revisão da rich picture

## Critérios de aceitação
Estar dentro dos padrões de uma rich picture

**Comment by Beatrizvn** [comment]
@ian-dcg @leonardogonmac A versão [1.0 da rich](https://github.com/Requisitos-de-Software/2023.1-Crunchyroll/blob/main/docs/pr%C3%A9-rastreabilidade/RichPictureCrunchyrollV1.0.pdf) picture está pronta para revisão.

**Comment by Mylena-angelica** [comment]
Rich picture revisada e documentação finalizada. As duas versões já contam na gitpage
