### ISSUE TITLE
Aplicativo selecionado

### ISSUE THREAD

**Issue by Beatrizvn** [Requisitos-de-Software/2023.1-Crunchyroll#7]
## Descrição
Falar sobre o aplicativo selecionado é o porquê da escolha dele.
## Tarefas
- [x] Falar sobre o aplicativo selecionado
- [x] O porquê da escolha dele

**Comment by Beatrizvn** [comment]
@leonardogonmac fiz a primeira tarefa, agora faz a parte de explicar o porquê da escolha do aplicativo

**Comment by leonardogonmac** [comment]
@Beatrizvn escrevi a explicação da escolha
se puder ler e me dar um feedback, agradeço

**Comment by Beatrizvn** [comment]
Acredito que esteja tudo certo após a revisão feita pelo @ian-dcg , vou fechar a issue
